# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Fixes the crash in AGP 9.0+
android.nonFinalResIds=true
android.nonTransitiveRClass=true

# Force use of your Homebrew Java 17
org.gradle.java.home=/opt/homebrew/Cellar/openjdk@17/17.0.19/libexec/openjdk.jdk/Contents/Home